backend:
  name: github
  repo: CurtisMac/webbuilderz
  branch: master
  base_url: https://us-central1-webbuilderz.cloudfunctions.net
  auth_endpoint: /oauth/auth

media_folder: src/data/uploads
public_folder: /uploads
publish_mode: editorial_workflow
site_url: https://webbuilderz.io
display_url: https://webbuilderz.io
logo_url: /logo.png

collections:
  - name: blog
    label: Blog
    folder: src/data/blog
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          hint: "Recommended size 1200px by 400px. Compress with https://tinyjpg.com/ before uploading.",
        }
      - {name: alt, label: Image alt tag, widget: string}
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author }
      - {
          name: pub_date,
          label: Published Date,
          widget: datetime,
          timeFormat: false,
        }
      - {
          name: update_date,
          label: Updated Date,
          widget: datetime,
          default: "",
          required: false,
        }
      - label: Categorize
        name: cats
        widget: object
        fields:
          - label: Category
            name: category
            widget: select
            options: ["Development", "Marketing", "How-To", "Coding", "custom - enter below"]
            hint: "If there is no appropriate option, select 'custom' and enter a custom category below"
          - {
            name: otherCat,
            label: Custom Category,
            widget: string,
            required: false,
          }
          - {
              name: tagList,
              label: List of Tags,
              widget: list,
              hint: "Seperate tags with a comma. Use lowercase only.",
            }
      - label: SEO
        name: seo
        widget: object
        fields:
          - {
              label: Meta Description,
              name: metaDesc,
              widget: text,
              hint: Displayed in search results. Recommend between 50-160 characters,
            }
  - name: pages
    label: Pages
    files:
      - label: About Page
        name: about
        file: src/data/content/about/about.yml
        fields:
          - { label: Title, name: aboutTitle, widget: string }
          - { label: Intro, name: aboutIntro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Role, name: role, widget: string }
              - { label: Bio, name: bio, widget: markdown }
              - { label: Photo, name: photo, widget: image }
          - label: Metadata
            name: metadata
            widget: object
            fields:
              - {
                  label: Meta Title,
                  name: metaTitle,
                  widget: string,
                  hint: Max length 60 characters,
                }
              - {
                  label: Meta Description,
                  name: metaDesc,
                  widget: text,
                  hint: Recommend between 50-160 characters,
                }
      - label: FAQ Page
        name: faq
        file: src/data/content/faq/faqPage.yml
        fields:
          - label: FAQ
            name: faq
            widget: list
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: text }
          - label: Metadata
            name: metadata
            widget: object
            fields:
              - {
                  label: Meta Title,
                  name: metaTitle,
                  widget: string,
                  hint: Max length 60 characters,
                }
              - {
                  label: Meta Description,
                  name: metaDesc,
                  widget: text,
                  hint: Recommend between 50-160 characters,
                }
      - label: Home Page
        name: home
        file: src/data/content/home/homePage.yml
        fields:
          - label: Metadata
            name: metadata
            widget: object
            fields:
              - {
                  label: Meta Title,
                  name: metaTitle,
                  widget: string,
                  hint: Max length 60 characters,
                }
              - {
                  label: Meta Description,
                  name: metaDesc,
                  widget: text,
                  hint: Recommend between 50-160 characters,
                }
          - label: Hero Section
            name: hero
            widget: object
            fields:
              - { label: Hero Text, name: heroText, widget: string }
              - { label: Hero Sub-Text, name: heroSubText, widget: text }
          - label: About Section
            name: about
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subTitle, widget: text }
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
          - label: Web Development
            name: webDev
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subTitle, widget: text }
              - { label: Text, name: text, widget: text }
              - label: Cards
                name: cards
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: string }
                  - label: Color
                    name: color
                    widget: select
                    default: pri1
                    options:
                      - { label: "Primary One (Main Yellow)", value: "pri1" }
                      - { label: "Primary Two (Dark Purple)", value: "pri2" }
                      - { label: "Primary Three (Teal)", value: "pri3" }
                      - { label: "Primary Four (Magenta)", value: "pri4" }
                      - { label: "Accent One (Chocolate)", value: "acc1" }
                      - { label: "Accent Two (Light Yellow)", value: "acc2" }
                      - { label: "Accent Three (Black)", value: "acc3" }
                      - { label: "Accent Four (Sky Blue)", value: "acc4" }
                  - { label: Image, name: image, widget: image }
          - label: Shopify
            name: shopify
            widget: object
            fields:
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
          - label: Partners
            name: partners
            widget: object
            fields:
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
              - label: Partner
                name: partner
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Link, name: link, widget: string }
                  - { label: Image, name: image, widget: image }
          - label: Digital Marketing
            name: marketing
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subTitle, widget: text }
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
              - label: Cards
                name: cards
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - label: Color
                    name: color
                    widget: select
                    default: pri1
                    options:
                      - { label: "Primary One (Main Yellow)", value: "pri1" }
                      - { label: "Primary Two (Dark Purple)", value: "pri2" }
                      - { label: "Primary Three (Teal)", value: "pri3" }
                      - { label: "Primary Four (Magenta)", value: "pri4" }
                      - { label: "Accent One (Chocolate)", value: "acc1" }
                      - { label: "Accent Two (Light Yellow)", value: "acc2" }
                      - { label: "Accent Three (Black)", value: "acc3" }
                      - { label: "Accent Four (Sky Blue)", value: "acc4" }
                  - { label: Image, name: image, widget: image }
          - label: Other Services
            name: other
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Cards
                name: cards
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: text }
                  - label: Color
                    name: color
                    widget: select
                    default: pri1
                    options:
                      - { label: "Primary One (Main Yellow)", value: "pri1" }
                      - { label: "Primary Two (Dark Purple)", value: "pri2" }
                      - { label: "Primary Three (Teal)", value: "pri3" }
                      - { label: "Primary Four (Magenta)", value: "pri4" }
                      - { label: "Accent One (Chocolate)", value: "acc1" }
                      - { label: "Accent Two (Light Yellow)", value: "acc2" }
                      - { label: "Accent Three (Black)", value: "acc3" }
                      - { label: "Accent Four (Sky Blue)", value: "acc4" }
                  - { label: Image, name: image, widget: image }
          - label: CTA
            name: cta
            widget: object
            fields:
              - { label: Tagline, name: text, widget: string }
              - label: Background Color
                name: bgColor
                widget: select
                default: pri1
                options:
                  - { label: "Primary One (Main Yellow)", value: "pri1" }
                  - { label: "Primary Two (Dark Purple)", value: "pri2" }
                  - { label: "Primary Three (Teal)", value: "pri3" }
                  - { label: "Primary Four (Magenta)", value: "pri4" }
                  - { label: "Accent One (Chocolate)", value: "acc1" }
                  - { label: "Accent Two (Light Yellow)", value: "acc2" }
                  - { label: "Accent Three (Black)", value: "acc3" }
                  - { label: "Accent Four (Sky Blue)", value: "acc4" }
              - { label: Button Text, name: button, widget: string }
              - label: Button Color
                name: btnColor
                widget: select
                default: pri1
                options:
                  - { label: "Primary One (Main Yellow)", value: "pri1" }
                  - { label: "Primary Two (Dark Purple)", value: "pri2" }
                  - { label: "Primary Three (Teal)", value: "pri3" }
                  - { label: "Primary Four (Magenta)", value: "pri4" }
                  - { label: "Accent One (Chocolate)", value: "acc1" }
                  - { label: "Accent Two (Light Yellow)", value: "acc2" }
                  - { label: "Accent Three (Black)", value: "acc3" }
                  - { label: "Accent Four (Sky Blue)", value: "acc4" }
  - name: legal
    label: Legal
    folder: src/data/content/legal
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {
          name: pub_date,
          label: Published Date,
          widget: datetime,
          timeFormat: false,
        }
      - {
          name: update_date,
          label: Updated Date,
          widget: datetime,
          default: "",
          required: false,
        }
  - name: misc
    label: Miscellaneous
    files:
      - label: Pricing
        name: pricing
        file: src/data/content/misc/pricing.yml
        fields:
          - label: Packages Collection
            name: packages
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - label: package
                name: Package
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - label: Price
                    name: price
                    widget: list
                    fields:
                      - { label: Currency, name: currency, widget: string }
                      - {
                          label: Amount,
                          name: amount,
                          widget: number,
                          valueType: int,
                        }
                  - label: Features
                    name: features
                    widget: list
                    fields:
                      - { label: Feature, name: feature, widget: string }
