backend:
  name: github
  repo: CurtisMac/webbuilderz
  branch: development
  base_url: https://us-central1-webbuilderz.cloudfunctions.net
  auth_endpoint: /oauth/auth

media_folder: src/data/uploads
public_folder: /uploads
publish_mode: editorial_workflow
site_url: https://webbuilderz.io
display_url: https://webbuilderz.io
logo_url: /logo.png

collections:
  - name: blog
    label: Blog
    folder: src/data/blog
    create: true
    fields:
      - { name: title, label: Title }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author }
      - {
          name: pub_date,
          label: Published Date,
          widget: datetime,
          timeFormat: false,
        }
      - {
          name: update_date,
          label: Updated Date,
          widget: datetime,
          default: "",
          required: false,
        }
      - { name: path, label: Path }
  - name: pages
    label: Pages
    files:
      - label: About Page
        name: about
        file: src/data/content/about/about.yml
        fields:
          - { label: Title, name: aboutTitle, widget: string }
          - { label: Intro, name: aboutIntro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Role, name: role, widget: string }
              - { label: Bio, name: bio, widget: markdown }
              - { label: Photo, name: photo, widget: image }
      - label: FAQ Page
        name: faq
        file: src/data/content/faq/faqPage.yml
        fields:
          - label: FAQ
            name: faq
            widget: list
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: text }
      - label: Home Page
        name: home
        file: src/data/content/home/homePage.yml
        fields:
          - label: Hero Section
            name: hero
            widget: object
            fields:
              - { label: Hero Text, name: heroText, widget: string }
              - { label: Hero Sub-Text, name: heroSubText, widget: text }
          - label: About Section
            name: about
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subTitle, widget: text }
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
          - label: Web Development
            name: webDev
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subTitle, widget: text }
              - { label: Text, name: text, widget: text }
              - label: Cards
                name: cards
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: string }
                  - label: Color
                    name: color
                    widget: select
                    default: pri1
                    options:
                      - { label: "Primary One (Main Yellow)", value: "pri1" }
                      - { label: "Primary Two (Dark Purple)", value: "pri2" }
                      - { label: "Primary Three (Teal)", value: "pri3" }
                      - { label: "Primary Four (Magenta)", value: "pri4" }
                      - { label: "Accent One (Chocolate)", value: "acc1" }
                      - { label: "Accent Two (Light Yellow)", value: "acc2" }
                      - { label: "Accent Three (Black)", value: "acc3" }
                      - { label: "Accent Four (Sky Blue)", value: "acc4" }
                  - { label: Image, name: image, widget: image }
          - label: Shopify
            name: shopify
            widget: object
            fields:
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
          - label: Digital Marketing
            name: marketing
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Sub Title, name: subTitle, widget: text }
              - { label: Text, name: text, widget: text }
              - { label: Image, name: image, widget: image }
              - label: Cards
                name: cards
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - label: Color
                    name: color
                    widget: select
                    default: pri1
                    options:
                      - { label: "Primary One (Main Yellow)", value: "pri1" }
                      - { label: "Primary Two (Dark Purple)", value: "pri2" }
                      - { label: "Primary Three (Teal)", value: "pri3" }
                      - { label: "Primary Four (Magenta)", value: "pri4" }
                      - { label: "Accent One (Chocolate)", value: "acc1" }
                      - { label: "Accent Two (Light Yellow)", value: "acc2" }
                      - { label: "Accent Three (Black)", value: "acc3" }
                      - { label: "Accent Four (Sky Blue)", value: "acc4" }
                  - { label: Image, name: image, widget: image }
          - label: Other Services
            name: other
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - label: Cards
                name: cards
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: Text, name: text, widget: text }
                  - label: Color
                    name: color
                    widget: select
                    default: pri1
                    options:
                      - { label: "Primary One (Main Yellow)", value: "pri1" }
                      - { label: "Primary Two (Dark Purple)", value: "pri2" }
                      - { label: "Primary Three (Teal)", value: "pri3" }
                      - { label: "Primary Four (Magenta)", value: "pri4" }
                      - { label: "Accent One (Chocolate)", value: "acc1" }
                      - { label: "Accent Two (Light Yellow)", value: "acc2" }
                      - { label: "Accent Three (Black)", value: "acc3" }
                      - { label: "Accent Four (Sky Blue)", value: "acc4" }
                  - { label: Image, name: image, widget: image }
          - label: CTA
            name: cta
            widget: object
            fields:
              - { label: Tagline, name: text, widget: string }
              - label: Background Color
                name: bgColor
                widget: select
                default: pri1
                options:
                  - { label: "Primary One (Main Yellow)", value: "pri1" }
                  - { label: "Primary Two (Dark Purple)", value: "pri2" }
                  - { label: "Primary Three (Teal)", value: "pri3" }
                  - { label: "Primary Four (Magenta)", value: "pri4" }
                  - { label: "Accent One (Chocolate)", value: "acc1" }
                  - { label: "Accent Two (Light Yellow)", value: "acc2" }
                  - { label: "Accent Three (Black)", value: "acc3" }
                  - { label: "Accent Four (Sky Blue)", value: "acc4" }
              - { label: Button Text, name: button, widget: string }
              - label: Button Color
                name: btnColor
                widget: select
                default: pri1
                options:
                  - { label: "Primary One (Main Yellow)", value: "pri1" }
                  - { label: "Primary Two (Dark Purple)", value: "pri2" }
                  - { label: "Primary Three (Teal)", value: "pri3" }
                  - { label: "Primary Four (Magenta)", value: "pri4" }
                  - { label: "Accent One (Chocolate)", value: "acc1" }
                  - { label: "Accent Two (Light Yellow)", value: "acc2" }
                  - { label: "Accent Three (Black)", value: "acc3" }
                  - { label: "Accent Four (Sky Blue)", value: "acc4" }
  - name: misc
    label: Miscellaneous
    files:
      - label: Pricing
        name: pricing
        file: src/data/content/misc/pricing.yml
        fields:
          - label: Packages Collection
            name: packages
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - label: package
                name: Package
                widget: list
                fields:
                  - { label: Name, name: name, widget: string }
                  - label: Price
                    name: price
                    widget: list
                    fields:
                      - { label: Currency, name: currency, widget: string }
                      - {
                          label: Amount,
                          name: amount,
                          widget: number,
                          valueType: int,
                        }
                  - label: Features
                    name: features
                    widget: list
                    fields:
                      - { label: Feature, name: feature, widget: string }
